spring.application.name=Database Demo
spring.datasource.url = jdbc:mysql://localhost:3306/shopping
spring.datasource.username = root
spring.datasource.password = Shy@m

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
